Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/crowdfund.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.crowdfund.com:7050
  - &FundraisersOrg
    Name: FundraisersMSP
    ID: FundraisersMSP
    MSPDir: ../organizations/peerOrganizations/fundraisers.crowdfund.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('FundraisersMSP.admin', 'FundraisersMSP.peer', 'FundraisersMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('FundraisersMSP.admin', 'FundraisersMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('FundraisersMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('FundraisersMSP.peer')"
  - &DonorsOrg
    Name: DonorsMSP
    ID: DonorsMSP
    MSPDir: ../organizations/peerOrganizations/donors.crowdfund.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DonorsMSP.admin', 'DonorsMSP.peer', 'DonorsMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('DonorsMSP.admin', 'DonorsMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('DonorsMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('DonorsMSP.peer')"
  - &AuthoritiesOrg
    Name: AuthoritiesMSP
    ID: AuthoritiesMSP
    MSPDir: ../organizations/peerOrganizations/authorities.crowdfund.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('AuthoritiesMSP.admin', 'AuthoritiesMSP.peer', 'AuthoritiesMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('AuthoritiesMSP.admin', 'AuthoritiesMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('AuthoritiesMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('AuthoritiesMSP.peer')"
  - &BankOrg
    Name: BankMSP
    ID: BankMSP
    MSPDir: ../organizations/peerOrganizations/bank.crowdfund.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('BankMSP.admin', 'BankMSP.peer', 'BankMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('BankMSP.admin', 'BankMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('BankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('BankMSP.peer')"

Capabilities:  
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true
    
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  Addresses:
    - orderer.crowdfund.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  FourOrgsChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.crowdfund.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/crowdfund.com/orderers/orderer.crowdfund.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/crowdfund.com/orderers/orderer.crowdfund.com/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *FundraisersOrg
        - *DonorsOrg
        - *AuthoritiesOrg
        - *BankOrg
      Capabilities: *ApplicationCapabilities
